---
- name: "Generate certificate"
  shell: "IPADDR=`ip addr show | grep 'eth' | grep -Po 'inet \\K[\\d.]+' | head -n 1`; openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /home/isucon/isucon2018-final/blackbox/nginx/_.isucon8.flying-chair.net.key -out /home/isucon/isucon2018-final/blackbox/nginx/_.isucon8.flying-chair.net.crt -subj '/C=JP/ST=Tokyo/L=Tokyo/O=ISUCON 9/OU=Web/CN='$IPADDR"
  become: yes
  become_user: isucon

- name: "Download generated certificate"
  fetch:
    src: /home/isucon/isucon2018-final/blackbox/nginx/_.isucon8.flying-chair.net.crt
    dest: /tmp/_.isucon8.flying-chair.net.crt
    flat: yes

- name: "Install isucoin.blackbox.service"
  copy:
    src: isucoin.blackbox.service
    dest: /etc/systemd/system/isucoin.blackbox.service
    owner: root
    group: root
    mode: 0644

- name: "Start isucoin.blackbox.service"
  systemd:
    state: started
    name: isucoin.blackbox.service
    enabled: yes
    daemon_reload: yes

