---
- name: "Install isucoin.service"
  copy:
    src: isucoin.service
    dest: /etc/systemd/system/isucoin.service
    owner: root
    group: root
    mode: 0644

- name: "Start isucoin.service"
  systemd:
    state: started
    name: isucoin.service
    enabled: yes
    daemon_reload: yes

- name: "Fixed endpoint"
  command: "mysql --protocol=TCP --host=localhost --port=13306 -uisucon -pisucon -e \"UPDATE setting SET val = 'https://{{ endpoint }}:5515' WHERE name = 'bank_endpoint'; UPDATE setting SET val = 'https://{{ endpoint }}:5516' WHERE name = 'log_endpoint'\" isucoin"
